spring.application.name=Spring-Boot-Notes

spring.data.mongodb.host = localhost

spring.data.mongodb.port = 27017

spring.data.mongodb.database = journaldb

spring.data.mongodb.auto-index-creation = true

#in production application we need to add username and password too
#spring.data.mongodb.username = username
#spring.data.mongodb.password = password;

